name: Rebaser
run-name: Rebaser

on:
  workflow_dispatch:

jobs:
  rebase:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: rebase
        run: |
          chmod u+x .github/rebaser.sh
          .github/rebaser.sh