name: Rebaser
run-name: Rebaser

on:
  push:
  workflow_dispatch:

jobs:
  rebase:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: rebase
        run: |
          mv .github/rebaser.sh ../rebaser.sh
          chmod u+x ../rebaser.sh
          ../rebaser.sh